
<h1 class="page-header">Lista sędziów:</h1>
<div class="col-lg-12">
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Nazwisko i Imię</th>
                    <th>Funkcja</th>
                </tr>
            </thead>
            <?php foreach ($sedziowie as $sedzia) : ?>
                <tr>
                    <td><?= $this->escapeHtml($sedzia->u_nazwisko) ?>&nbsp;&nbsp;<?= $this->escapeHtml($sedzia->u_imie) ?></td>
                    <td><?= $this->escapeHtml($sedzia->u_funkcja) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>



