<h1 class="page-header">Edycja nazwy zespołu</h1>
<div class="col-lg-6">
    <form enctype="multipart/form-data" action="<?= $this->url('kadra', array('action' => 'edytuj', 'id' => $kadra->id_zespol)); ?>" method="post">
        <div class="form-group">
            <label>Nazwa klubu:</label>
            <input class="form-control" name="Nazwa_zespolu" placeholder="Nazwa klubu" value="<?= $kadra->nazwa_zespolu; ?>" />
        </div>

        <a href="<?= $this->url('kadra', array()); ?>"><input class="btn btn-default" type="button" value="Wstecz" />
            <button type="submit" class="btn btn-default">Zatwierdź</button>
            <button type="reset" class="btn btn-default">Wyczyść</button>
        </a>
    </form>
</div>
