<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-type" content="text/html; charset=iso-8859-2">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>EXTRANET 2.0</title>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
        <link rel="stylesheet" href="http://bootsnipp.com/dist/bootsnipp.min.css?ver=7d23ff901039aef6293954d33d23c066">
        <style> 

            .panel-login {
                border-color: #ccc;
                -webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
                -moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
                box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);
            }
            .panel-login>.panel-heading {
                color: #00415d;
                background-color: #fff;
                border-color: #fff;
                text-align:center;
            }
            .panel-login>.panel-heading a{
                text-decoration: none;
                color: #666;
                font-weight: bold;
                font-size: 15px;
                -webkit-transition: all 0.1s linear;
                -moz-transition: all 0.1s linear;
                transition: all 0.1s linear;
            }
            .panel-login>.panel-heading a.active{
                color: #029f5b;
                font-size: 18px;
            }
            .panel-login>.panel-heading hr{
                margin-top: 10px;
                margin-bottom: 0px;
                clear: both;
                border: 0;
                height: 1px;
                background-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));
                background-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
                background-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
                background-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
            }
            .panel-login input[type="text"],.panel-login input[type="email"],.panel-login input[type="password"] {
                height: 45px;
                border: 1px solid #ddd;
                font-size: 16px;
                -webkit-transition: all 0.1s linear;
                -moz-transition: all 0.1s linear;
                transition: all 0.1s linear;
            }
            .panel-login input:hover,
            .panel-login input:focus {
                outline:none;
                -webkit-box-shadow: none;
                -moz-box-shadow: none;
                box-shadow: none;
                border-color: #ccc;
            }
            .btn-login {
                background-color: #59B2E6;
                outline: none;
                color: #fff;
                font-size: 14px;
                height: auto;
                font-weight: normal;
                padding: 14px 0;
                text-transform: uppercase;
                border-color: #59B2E6;
            }
            .btn-login:hover,
            .btn-login:focus {
                color: #fff;
                background-color: #53A3CD;
                border-color: #53A3CD;
            }
            .forgot-password {
                text-decoration: underline;
                color: #888;
            }
            .forgot-password:hover,
            .forgot-password:focus {
                text-decoration: underline;
                color: #666;
            }

            .btn-register {
                background-color: #1CB94E;
                outline: none;
                color: #fff;
                font-size: 14px;
                height: auto;
                font-weight: normal;
                padding: 14px 0;
                text-transform: uppercase;
                border-color: #1CB94A;
            }
            .btn-register:hover,
            .btn-register:focus {
                color: #fff;
                background-color: #1CA347;
                border-color: #1CA347;
            }
        </style>

        <link href="<?= $this->basePath() . '/css/bootstrap.min.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/css/sb-admin-2.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/font-awesome/css/font-awesome.min.css' ?>" rel="stylesheet" type="text/css"> 
        <script src="<?= $this->basePath() . '/js/jquery.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/bootstrap.min.js' ?>"></script>   
        <script type="text/javascript">
            $(function () {

                $('#login-form-link').click(function (e) {
                    $("#login-form").delay(100).fadeIn(100);
                    $("#register-form").fadeOut(100);
                    $('#register-form-link').removeClass('active');
                    $(this).addClass('active');
                    e.preventDefault();
                });
                $('#register-form-link').click(function (e) {
                    $("#register-form").delay(100).fadeIn(100);
                    $("#login-form").fadeOut(100);
                    $('#login-form-link').removeClass('active');
                    $(this).addClass('active');
                    e.preventDefault();
                });

            });

        </script>
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" id="up-nav" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-brand">EXTRANET 2.0</a>
                </div>
            </nav>
            <div id="page-wrapper" style="margin: auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">
                                <?= $this->title; ?>
                            </h1>
                        </div>
                    </div>
                    <h2><center>Witaj w internetowym systemie EXTRANET 2 </center></h2>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="panel panel-login">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <a href="<?= $this->url('login'); ?>" class="active" id="login-form-link">Logowanie</a>
                                            </div>
                                            <div class="col-xs-6">
                                                <a href="<?= $this->url('register'); ?>" id="register-form-link">Rejestracja</a>
                                            </div>
                                        </div>
                                        <hr>
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <form id="login-form" action="http://<?= $_SERVER['HTTP_HOST'] . $this->url('login'); ?>" method="post" role="form" style="display: block;">
                                                    <div class="form-group">
                                                        <input type="text" name="login" id="username" tabindex="1" class="form-control" placeholder="Login" value="">
                                                    </div>
                                                    <div class="form-group">

                                                        <input type="password" name="pwd" id="password" tabindex="2" class="form-control" placeholder="Hasło">
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="row">
                                                            <div class="col-sm-6 col-sm-offset-3">
                                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login"  value="Zaloguj się">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                <form id="register-form" action="http://<?= $_SERVER['HTTP_HOST'] . $this->url('register'); ?>" method="post" role="form" style="display: none;">
                                                    <div class="form-group">
                                                        <input type="text" name="Nazwisko" id="username" tabindex="1" class="form-control" placeholder="Nazwisko" value="">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="text" name="Imie" id="username" tabindex="1" class="form-control" placeholder="Imie" value="">
                                                    </div>

                                                    <div class="form-group"> 
                                                        <label>Funkcja:</label><br>
                                                        <input onclick="document.getElementById('klub').disabled = false;" type="radio" name="Funkcja" value="dzialacz" checked > Działacz sportowy<br>
                                                        <input onclick="document.getElementById('klub').disabled = true;" type="radio" name="Funkcja" value="sedzia" > Sędzia piłkarski<br>
                                                    </div>
                                                    <div class="form-group">
                                                        <select name= "Id_zespol" id="klub" class="form-control" placeholder="Klub">
                                                            <option value="" disabled selected>Wybierz klub</option>
                                                            <?php foreach ($this->kluby as $klub) { ?>
                                                                <option value="<?= $klub->id_zespol ?>"><?= $klub->nazwa_zespolu ?></option>
                                                            <?php } ?>
                                                        </select>
                                                    </div>                                                            
                                                    <div class="form-group">
                                                        <input type="email" name="Email" id="email" tabindex="1" class="form-control" placeholder="Email" value="">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="text" name="Login" id="username" tabindex="1" class="form-control" placeholder="Login" value="">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="password" name="Haslo" id="password" tabindex="2" class="form-control" placeholder="Hasło">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="password" name="Powtorz_haslo" id="confirm-password" tabindex="2" class="form-control" placeholder="Powtórz hasło">
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="row">
                                                            <div class="col-sm-6 col-sm-offset-3">
                                                                <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Zarejestruj się">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

