<h1 class="page-header">Edycja zawodnika</h1>
<div class="col-lg-6">
    <form enctype="multipart/form-data" action="<?= $this->url('zawodnik', array('action' => 'edytuj', 'id' => $zawodnik->id_zawodnik)); ?>" method="post">

        <div class="form-group">
            <label>Imie:</label>
            <input name="Imie_zawodnika" class="form-control" placeholder="Imie" value="<?= $zawodnik->z_imie; ?>" />
        </div>
        <div class="form-group">
            <label>Nazwisko:</label>
            <input name="Nazwisko_zawodnika" class="form-control" placeholder="Nazwisko" value="<?= $zawodnik->z_nazwisko; ?>"/>
        </div> 

        <div class="form-group">
            <label>Data urodzenia:</label>
            <input name="Data_ur" type="text" id="date" class="span1" value="<?= $zawodnik->z_data_ur; ?>" readonly required>
        </div>

        <div class="form-group">
            <label>Klub:</label>
            <select name="Klub" class="form-control">
                <?php foreach ($kluby as $klub) { ?>
                    <option value="<?= $klub->id_zespol ?>" <?php if ($klub->id_zespol == $zawodnik->id_zespol) {
                    echo 'selected';
                } ?>><?= $klub->nazwa_zespolu ?></option>
<?php } ?>
            </select>
        </div>

        <a href="<?= $this->url('zawodnik', array()); ?>"><input class="btn btn-default" type="button" value="Wstecz" />
            <button type="submit" class="btn btn-default">Zatwierdź</button>
            <button type="reset" class="btn btn-default">Wyczyść</button>
        </a>
    </form>
</div> 

<script type="text/javascript">
    $("#date").datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
    }).on('changeDate', function (ev) {
        $(this).datepicker('hide');
    });
</script>